=== TheSpuc/workspaces/sadp/XMLSchema/src/xmlSchemaAss1/BookSchema.xsd
<?xml version="1.0"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
	targetNamespace="http://www.w3schools.com" xmlns="http://www.w3schools.com"
	elementFormDefault="qualified">

	<xs:element name="Book" type="Content" />

	<xs:complexType name="Content">
		<xs:sequence>
			<xs:element name="Chapter" maxOccurs="unbounded"
				minOccurs="1" type="Chapter" />
		</xs:sequence>
	</xs:complexType>

	<xs:complexType name="Chapter">
		<xs:sequence>
			<xs:element name="title" type="xs:string" />
			<xs:element name="Section" maxOccurs="unbounded" minOccurs="1"
				type="Section" />
		</xs:sequence>
	</xs:complexType>

	<xs:complexType name="Section">
		<xs:sequence>
			<xs:element name="title" type="xs:string" />
		</xs:sequence>
	</xs:complexType>
</xs:schema>

=== TheSpuc/workspaces/sadp/XMLSchema/src/xmlSchemaAss1/BookSchema.xml
<?xml version="1.0" encoding="UTF-8"?>
<p:Book xmlns:p="http://www.w3schools.com" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://www.w3schools.com BookSchema.xsd ">
	<p:Chapter>
		<p:title>p:title</p:title>
		<p:Section>
			<p:title>p:title</p:title>
		</p:Section>
	</p:Chapter>
	<p:Chapter>
		<p:title></p:title>
		<p:Section>
			<p:title></p:title>
		</p:Section>
	</p:Chapter>
</p:Book>
